language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  include:
  - python: "3.5"
    env: NEW_PIP=1

script:
  # Upgrade to at least pip 10, to test against that as well
  - if [[ "$NEW_PIP" ]]; then pip install --upgrade "pip>=10" a; fi
  # Flake8 requires setuptools > 30, but some preinstalled are to old for that
  - pip install --upgrade setuptools
  - python setup.py test
  - coverage run setup.py test

notifications:
  email: false
before_install:
  - pip install codecov flake8
  - |
    for i in 3 4 5 6 7 8 9 10
    do
        wget https://hg.python.org/cpython/raw-file/v3.6.0/Lib/test/badsyntax_future$i.py -O badsyntax_future$i.py
    done
after_success:
  - codecov
